package cmd

import (
	"fmt"
	"github.com/ShellBear/epical/pkg/epical"
	"github.com/spf13/cobra"
)

var clearCmd = &cobra.Command{
	Use:   "clear",
	Short: "Clear all calendar events generated by Epical",
	Run: func(cmd *cobra.Command, args []string) {
		epical.ClearEvents(cmd.Flag("credentials").Value.String())
		fmt.Println("Successfully cleared calendar events.")
	},
}
